### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/http2#134]
@edsko @FinleyMcIlwaine To release a new version, we should agree with/check:

- Version number: 5.2.7 in the sense of no API change or 5.3.0 in the sense of behavior change of workers.
- Server performance: does your server keep the throughput?
- Should we fix  #129?

**Comment by FinleyMcIlwaine** [comment]
I think the change in behavior is enough to warrant a bump to 5.3.0. I am not sure yet whether our throughput has been affected. Once I determine what is going on with [the empty data frames in our benchmark](https://github.com/well-typed/grapesy/issues/177#issuecomment-2224070875) I will be able to do throughput tests.

As I'm debugging that benchmark, I am still seeing these kinds of window updates in wireshark:

![Screenshot 2024-07-11 at 3 43 57 PM](https://github.com/user-attachments/assets/18ea523b-f134-44f0-9737-0ab80e057e22)

I believe this shows three packets holding six consecutive window updates for the same stream, one being a 9 byte increment, and the rest varying in size from 4069 bytes to 36783 bytes. Does this look like expected behavior? Either way, the small window updates doesn't seem like big enough deal to hold up this release.

Thanks for looping us in @kazu-yamamoto!

**Comment by kazu-yamamoto** [comment]
The version has bumped to 5.3.0 on the `main` branch.

The behavior of window update is not what I expect.
I should dig it.

**Comment by kazu-yamamoto** [comment]
Now I can reproduce the window issue.
Let me consider how to fix it.

**Comment by FinleyMcIlwaine** [comment]
@kazu-yamamoto We have submitted some patches that fix the empty data frames we were seeing. It would be ideal if those patches were included in the next releases of `http2` and `http-semantics`. If those are in, I think we are ready for a release.

**Comment by kazu-yamamoto** [comment]
@edsko @FinleyMcIlwaine I'm going to release the following packages:

- http-semantics v0.2.0
- http2 v5.3.0
- http2-tls v0.4.1

Any objections?

I would like to release `network-control` when the small window update is fixed.

**Comment by FinleyMcIlwaine** [comment]
@kazu-yamamoto Looks good to us!

**Comment by kazu-yamamoto** [comment]
The four packages above have been released.
Thank you for your contribution!
