### ISSUE TITLE
SETTINGS_MAX_FRAME_SIZE

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/http2#45]
@epoberezkin

- `SETTINGS_MAX_FRAME_SIZE` is implemented as `maxFrameSize` in `defaultSettings`.
- This can be updated by its peer of *other* implementation.
- Haskell API does not provide API to change its value at all.
- `decodeFrame` uses it to check the limit.
- But `Sender` does not use the limit at all.
- So, both client and server is Haskell, there is not way to change the default value (16K). And it's possible that one side send a frame over 16K resulting in an error in the other side.

**Comment by kazu-yamamoto** [comment]
This observation may be wrong. I will dig into it deeper tomorrow.

**Comment by epoberezkin** [comment]
I've figured out empirically that more than 16k is not supported, so now they are all certainly exactly 16k :) And in case there is a shorter frame, as I have some concurrency issue I don't understand yet, a shorter frame I have in one case I am padding to 16kb - somehow it fixes concurrency problem...

What I didn't understand - is it something we could add a support for - is it what this issue is about?

Also, it might be wrong to expect that, and it's definitely a separate improvement, but it would be cool to:
- support any size byte strings automatically chunked to max size frames - my first attempt was to just give a large body to the library.
- accept request size as a separate parameter, so one doesn't have to remember what is the correct header name...

**Comment by kazu-yamamoto** [comment]
To let small frames go out to network, you should use the `flush` function.
If they don't go out, it's a bug.
I need to prepare a test case, anyway.

**Comment by epoberezkin** [comment]
> To let small frames go out to network, you should use the flush function.

I certainly do, and it works in case I add some arbitrary delays... There is come concurrency issue, not sure where. The root cause might be that client sendRequest function cannot be used concurrently - you need to wait until it returns and then receive the whole body before you can use it again. So in concurrent systems you need to have some queueing mechanism to avoid concurrent calls to sendRequest.

**Comment by kazu-yamamoto** [comment]
Fixed via #44.
