### ISSUE TITLE
Resource control

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/http2#98]
To control the amount of resource (mainly memory) to be used in the server side, the following parameters should be provided:

- The number of workers
- The max window sizes both for streams and connections
- The max concurrency of streams

For this, I will introduce `ServerConfig` and provide:

```haskell
run' :: ServerConfig -> Config -> Server -> IO ()
```

To keep backward compatibility, `run` should be as follows:

```haskell
run :: Config -> Server -> IO ()
run = run' defaultServerConfig
```

Cc: @edsko and @epoberezkin

**Comment by edsko** [comment]
Makes sense. (Just for the record, personally I'm also fine with a version where there isn't the `run`/`run'` distinction, I can just set a lower bound. Up to you.)

**Comment by akshaymankar** [comment]
Should the number of workers and max concurrency of streams be the same number? It so happens that I was testing this today and found that if 3 requests are stuck on the server (because the server has only 3 workers), next requests just get blocked without any warning. I am guessing they would get processes as soon as a worker is free, but at that point it is faster for the client to make another connection so if it knew from the max concurrency setting, it could make this decision.

**Comment by kazu-yamamoto** [comment]
In my opinion, the number of workers should be smaller than the max streams.
10 (not 3) and 100 would be nice default values.
If worker's jobs are light, contention against input queue are visible.
If workers jobs are heavy, the contention is invisible.
So the larger workers, the better.
It's hard to choose proper default values for any situations.

**Comment by kazu-yamamoto** [comment]
@akshaymankar BTW, I'm not tackling #71.

**Comment by akshaymankar** [comment]
> If worker's jobs are light, contention against the input queue are visible.
If workers jobs are heavy, the contention is invisible.
So the larger number of workers, the better.
It's hard to choose proper default values for any situations.

This makes a lot of sense. Thanks for clarifying!

**Comment by kazu-yamamoto** [comment]
Closing.
